
Status: FAILED!
Reason: Unable to run right.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-27b195fd-3caa-4055-9ab7-0db90836b126/9780357881019-fundamentals-of-python-3e-27b195fd-3caa-4055-9ab7-0db90836b126/python/chapter3/ex02/right.py", line 6, in <module>
    sides=[a,b,c].sorted()
          ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'sorted'. Did you mean: 'sort'?

Timestamp: 2025-01-28 23:29:22.631755

Status: FAILED!
Reason: Unable to run right.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-27b195fd-3caa-4055-9ab7-0db90836b126/9780357881019-fundamentals-of-python-3e-27b195fd-3caa-4055-9ab7-0db90836b126/python/chapter3/ex02/right.py", line 6, in <module>
    sides=[a,b,c].sorted()
          ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'sorted'. Did you mean: 'sort'?

Timestamp: 2025-01-28 23:29:22.631856

Status: FAILED!
Reason: Unable to run right.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-27b195fd-3caa-4055-9ab7-0db90836b126/9780357881019-fundamentals-of-python-3e-27b195fd-3caa-4055-9ab7-0db90836b126/python/chapter3/ex02/right.py", line 6, in <module>
    sides=[a,b,c].sorted()
          ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'sorted'. Did you mean: 'sort'?

Timestamp: 2025-01-28 23:29:22.733834

Status: FAILED!
Reason: Unable to run right.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357881019-fundamentals-of-python-3e-27b195fd-3caa-4055-9ab7-0db90836b126/9780357881019-fundamentals-of-python-3e-27b195fd-3caa-4055-9ab7-0db90836b126/python/chapter3/ex02/right.py", line 6, in <module>
    sides=[a,b,c].sorted()
          ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'sorted'. Did you mean: 'sort'?

Timestamp: 2025-01-28 23:29:22.733902
